
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore backend/src/Planty.API/Planty.API.csproj
    
    - name: Build
      run: dotnet build backend/src/Planty.API/Planty.API.csproj --no-restore --configuration Release
    
    - name: Test
      run: dotnet test backend/src/Planty.API/Planty.API.csproj --no-build --configuration Release --verbosity normal